# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 548a401856bd00ae0d22867131a387ab47629b7dae5aadd7fc7c752ea3d888da48c3a095847c71efa38073dfbd7eb2c520f1260f1c4f780949b74d7002309d16

test:
  secret_key_base: c588d5158873523272b92681303b49b5b8be3e7b5f2353fe4fb7348eb004c96b63232f6a0caed34cd4efc83b4a844d45933b6cdfb7217f4d491d86ae1d198ff4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
